# https://taskfile.dev - For Augur Hakesch

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  init:
    cmds:
      - task: init-frontend
      - curl -o ./src/api/data/dir_3x3_3.tif https://www.suter-burri.ch/dateien/augur/dir_3x3_3.tif

  init-frontend:
    dir: src/frontend
    cmds:
      - gulp build

  dev:
    cmds:
      - docker compose up --build

  dev-frontend:
    dir: src/frontend
    cmds:
      - gulp

  build:
    cmds:
      - docker compose build
  
  build-frontend:
    dir: src/frontend
    cmds:
      - gulp build

  push:
    cmds:
      - task: build
      - docker compose push
