# https://taskfile.dev - For Augur Hakesch

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  init:
    cmds:
      - task: init-frontend
      - mkdir src/api/data
      - mkdir src/api/data/temp
      - curl -o src/api/data/dir_3x3_3.tif https://www.suter-burri.ch/dateien/augur/dir_3x3_3.tif

  init-frontend:
    dir: src/frontend
    cmds:
      - npm i

  dev:
    cmds:
      - docker compose up --build

  dev-frontend:
    dir: src/frontend
    cmds:
      - npm run dev

  build:
    cmds:
      - docker compose build
  
  build-frontend:
    dir: src/frontend
    cmds:
      - npm run build

  push:
    cmds:
      - task: build
      - docker compose push

  prisma:
    dir: src/frontend
    cmds:
      - prisma generate --schema=../frontend/prisma/schema.prisma